# Decompositions

 ## Eigenvalues and eigenvectors

In [64]:
# A matrix decomposition or matrix factorization is a
# factorization of a matrix into a product of matrices
# help(linalg.eig)
import numpy as np
from scipy import linalg

A = np.array([[4, 5], [2, 3]])
# Solve an ordinary or generalized eigenvalue problem 
# of a square matrix
la, v = linalg.eig(A)

# eigenvalues
print(la) # linalg.eigvals(A)

# right eigenvectors
print(v[:, 0]) # first eigenvector
print(v[:, 1]) # second eigenvector

[6.70156212+0.j 0.29843788+0.j]
[0.87979045 0.47536171]
[-0.80372182  0.59500525]


## Singular value decomposition

In [23]:
# Assuming, numpy as np and scipy.linalg imported

X = np.array([[5, 6, 7], [4, 3, 2]])
M, N = X.shape
# Singular Value Decomposition
U, s, Vh = linalg.svd(X)
# Construct the sigma matrix in SVD from singular values and size M, N
Sig = linalg.diagsvd(s, M, N)
print(U, Sig, Vh)
print(U.dot(Sig.dot(Vh))) # checking computation      

[[-0.89846137 -0.43905258]
 [-0.43905258  0.89846137]] [[11.63661999  0.          0.        ]
 [ 0.          1.89448549  0.        ]] [[-0.53697011 -0.57644969 -0.61592926]
 [ 0.73823873  0.03223494 -0.67376886]
 [ 0.40824829 -0.81649658  0.40824829]]
[[5. 6. 7.]
 [4. 3. 2.]]


## LU Decomposition

In [28]:
# Assuming, numpy as np and scipy.linalg imported

Y = np.array([[3, 4, 5, 6], [2, 3, 4, 5]])
# Compute pivoted LU decomposition of a matrix
#
# P is a permutation matrix, L lower triangular with unit
# diagonal elements, and U upper triangular.
p, l, u = linalg.lu(Y)

print(p, '\n\n', l, '\n\n',  u)

[[1. 0.]
 [0. 1.]] 

 [[1.         0.        ]
 [0.66666667 1.        ]] 

 [[3.         4.         5.         6.        ]
 [0.         0.33333333 0.66666667 1.        ]]


## Cholesky decomposition

In [45]:
# Assuming, numpy as np and scipy.linalg imported

A = np.array([[4, -7j], [3j, 6]])
B = np.array([[4, 5], [2, 7]])

# Compute the Cholesky decomposition of a matrix
L = linalg.cholesky(A, lower=True)

print(L, '\n')
print(L @ L.T.conj())

[[2.        +0.j  0.        +0.j ]
 [0.        +1.5j 1.93649167+0.j ]] 

[[4.+0.j 0.-3.j]
 [0.+3.j 6.+0.j]]


## QR decomposition

In [57]:
# Assuming, numpy as np and scipy.linalg imported
from scipy import allclose
# Calculate the decomposition ``A = Q R`` where Q 
# is unitary/orthogonal and R upper triangular
a = np.random.randn(4, 8)

q, r = linalg.qr(a) # mode='full'
# allclose(a, q @ r) # True
print(q, r)

r2 = linalg.qr(a, mode='r')
# allclose(r, r2) # True
# help(linalg.qr)

[[-0.47289654 -0.43964679 -0.65850007 -0.38659698]
 [ 0.75121119 -0.48325088  0.04575619 -0.44727698]
 [ 0.1011651   0.73545853 -0.18576766 -0.64370548]
 [ 0.44923962  0.17966645 -0.72785603  0.4859314 ]] [[ 2.90385848 -0.51703513  0.80787654  1.16588604  1.47222036  0.09559155
   1.39781295 -1.2245903 ]
 [ 0.         -1.02671409  0.12344472 -0.9825988  -1.21068879  1.81746602
   0.51686243 -1.17139365]
 [ 0.          0.          1.63116     0.063373    0.43376926  1.68481712
  -0.29861887 -0.44832639]
 [ 0.          0.          0.          1.30166552  0.74194181 -0.42847715
   0.19178222  0.71456357]]


## Schur decomposition

In [67]:
# Assuming, numpy as np and scipy.linalg imported

matrix1 = np.mat('[1 2 3; 4 5 7; 1 0 3]') # matrix

T, Z = linalg.schur(A)
print(T, Z)

T2, Z2 = linalg.schur(A, output='complex')
print(T2, Z2)

print(linalg.eigvals(T2))
print(T - T2) # help(linalg.schur)

[[6.70156212 3.        ]
 [0.         0.29843788]] [[ 0.87979045 -0.47536171]
 [ 0.47536171  0.87979045]]
[[6.70156212+0.j 3.        +0.j]
 [0.        +0.j 0.29843788+0.j]] [[ 0.87979045+0.j -0.47536171+0.j]
 [ 0.47536171+0.j  0.87979045+0.j]]
[6.70156212+0.j 0.29843788+0.j]
[[ 0.00000000e+00+0.j -4.44089210e-16+0.j]
 [ 0.00000000e+00+0.j  2.22044605e-16+0.j]]


### That's all for now
seek help as per requirement