## Matrix Exponential Functions

In [15]:
import numpy as np
from scipy import linalg

a = np.array([[3., 4.], [2., 3.]])

# Compute matrix logarithm.
x = linalg.logm(a)

# Verify expm(logm(a)) returns a
a2 = linalg.expm(x)

print(x,'\n\n', a2)

[[2.22044605e-16 2.49290096e+00]
 [1.24645048e+00 8.88178420e-16]] 

 [[3. 4.]
 [2. 3.]]


## Matrix Trigonometric Functions

In [28]:
# Assuming, numpy as np and scipy.linalg imported

a = np.array([[1.0, 2.0], [-1.0, 3.0]])

t = linalg.tanm(a) # matrix cosine

s = linalg.sinm(a) # matrix sine
c = linalg.cosm(a) # matrix cosine

t2 = s.dot(linalg.inv(c)) # matrix tangent
print(t, '\n\n', t2, '\n\n', s, '\n\n', c)

[[-1.41019446  2.33347251]
 [-1.16673626  0.92327806]] 

 [[-1.41019446  2.33347251]
 [-1.16673626  0.92327806]] 

 [[ 1.89217551 -0.97811252]
 [ 0.48905626  0.91406299]] 

 [[ 0.4264593  -2.13721484]
 [ 1.06860742 -1.71075555]]


## Matrix Hyperbolic Trigonometric Functions

In [33]:
# Assuming, numpy as np and scipy.linalg imported

a = np.array([[2, 6], [3, 8]])

# Compute the hyperbolic matrix sine
shm = linalg.sinhm(a)
chm = linalg.coshm(a)
thm = linalg.tanhm(a)

verify_thm = shm.dot(linalg.inv(chm))

print(shm,'\n\n', chm, '\n\n', thm, '\n\n', verify_thm)

[[ 2831.58406478  7736.57087241]
 [ 3868.28543621 10568.1549372 ]] 

 [[ 2832.54366344  7735.86842475]
 [ 3867.93421238 10568.4120882 ]] 

 [[0.05857833 0.68916849]
 [0.34458424 0.74774682]] 

 [[0.05857833 0.68916849]
 [0.34458424 0.74774682]]


## Matrix Arbitrary function

In [43]:
## Assuming, numpy as np and scipy.linalg imported

a = np.array([[4, 2], [5, 1]])

# Evaluate a matrix function specified by a callable
x = linalg.funm(a, lambda x: x**2)

print(x, '\n')

# alternative of above function
print(a @ a) # a.dot(a)

[[26. 10.]
 [25. 11.]] 

[[26 10]
 [25 11]]
