## Block Diagonal Matrix

In [1]:
import numpy as np
from scipy import linalg

A = np.array([[0, 1],[1, 0]])
B = np.array([[3, 6], [2, 9]])
C = np.array([[5]])
X = np.ones((2, 3))

bdm = linalg.block_diag(A, B, C)
bdm2 = linalg.block_diag(A, B, C, X)

print(bdm, '\n\n', bdm2)

[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 3 6 0]
 [0 0 2 9 0]
 [0 0 0 0 5]] 

 [[0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 3. 6. 0. 0. 0. 0.]
 [0. 0. 2. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 5. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1.]]


## Circulant Matrix 

In [5]:
# Assuming, numpy as np and scipy.linalg imported

# Construct a circulant matrix
c1 = linalg.circulant([2, 4, 6])

c2 = linalg.circulant([2, 1, 3])

print(c1, '\n\n', c2)

[[2 6 4]
 [4 2 6]
 [6 4 2]] 

 [[2 3 1]
 [1 2 3]
 [3 1 2]]


## Companion Matrix

In [11]:
# Assuming, numpy as np and scipy.linalg imported

# Create a companion matrix
cmp1 = linalg.companion([1, 6, -3, 0])

cmp2 = linalg.companion([3, 4, 5, 6])

print(cmp1, '\n\n', cmp2)

[[-6.  3.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]] 

 [[-1.33333333 -1.66666667 -2.        ]
 [ 1.          0.          0.        ]
 [ 0.          1.          0.        ]]


## Hadamard Matrix

In [21]:
# Assuming, numpy as np and scipy.linalg imported

# Constructs an n-by-n Hadamard matrix, using Sylvester's
# construction.  `n` must be a power of 2
h1 = linalg.hadamard(2)
h2 = linalg.hadamard(2, dtype='complex')
h3 = linalg.hadamard(4, dtype='float')

print(h1, '\n\n', h2, '\n\n', h3)

[[ 1  1]
 [ 1 -1]] 

 [[ 1.+0.j  1.+0.j]
 [ 1.+0.j -1.-0.j]] 

 [[ 1.  1.  1.  1.]
 [ 1. -1.  1. -1.]
 [ 1.  1. -1. -1.]
 [ 1. -1. -1.  1.]]


## Hankel Matrix

In [24]:
# Assuming, numpy as np and scipy.linalg imported

# The Hankel matrix has constant anti-diagonals, with `c` as its
# first column and `r` as its last row.  If `r` is not given, then
# `r = zeros_like(c)` is assumed
h1 = linalg.hankel([3, 5, 7])
h2 = linalg.hankel([2, 4, 6], [6, 7, 8])

print(h1, '\n\n', h2)

[[3 5 7]
 [5 7 0]
 [7 0 0]] 

 [[2 4 6]
 [4 6 7]
 [6 7 8]]


## Hilbert Matrix

In [30]:
# Assuming, numpy as np and scipy.linalg imported

# Create a Hilbert matrix of order `n`.
# Returns the `n` by `n` array with entries `h[i,j] = 1 / (i + j + 1)`

hl1 = linalg.hilbert(2)
hl2 = linalg.hilbert(2)

print(hl1,'\n\n', hl2)

[[1.         0.5       ]
 [0.5        0.33333333]] 

 [[1.         0.5       ]
 [0.5        0.33333333]]


## Inverse Hilbert Matrix

In [42]:
# Assuming, numpy as np and scipy.linalg imported

# Inverse of Hilbert
hli = linalg.invhilbert(4)
hli2 = linalg.invhilbert(4, exact=True)

print(hli, '\n\n', hli2)
print(linalg.invhilbert(16)[5][6])
print(linalg.invhilbert(16, exact=True)[5][6])

[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]] 

 [[   16  -120   240  -140]
 [ -120  1200 -2700  1680]
 [  240 -2700  6480 -4200]
 [ -140  1680 -4200  2800]]
-4.8682817765565984e+17
-486828177655659840


## Leslie Matrix

In [48]:
# Assuming, numpy as np and scipy.linalg imported

# Create a Leslie matrix

# Given the length n array of fecundity coefficients `f` and
# the length n-1 array of survival coefficients `s`, return 
# the associated Leslie matrix.
x = linalg.leslie([1, 2, 3, 4], [5, 6, 7])

y = linalg.leslie([1, 2, 3], [-3, 2])

print(x, '\n\n', y)

[[1 2 3 4]
 [5 0 0 0]
 [0 6 0 0]
 [0 0 7 0]] 

 [[ 1  2  3]
 [-3  0  0]
 [ 0  2  0]]


## Pascal Matrix

In [56]:
# Assuming, numpy as np and scipy.linalg imported

# The Pascal matrix is a matrix containing the binomial 
# coefficients as its elements
pa1 = linalg.pascal(4) # kind='symmetric'
pa2 = linalg.pascal(4, kind='lower')

print(pa1, '\n\n', pa2, '\n')
print(linalg.pascal(15)[-1, -1])

[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  3  6 10]
 [ 1  4 10 20]] 

 [[1 0 0 0]
 [1 1 0 0]
 [1 2 1 0]
 [1 3 3 1]] 

40116600


## Toeplitz Matrix

In [66]:
# Assuming, numpy as np and scipy.linalg imported

# The Toeplitz matrix has constant diagonals, with c 
# as its first column and r as its first row.  
# If r is not given, ``r == conjugate(c)`` is assumed
toe1 = linalg.toeplitz([2, 3, 4])
toe2 = linalg.toeplitz([2, 3, 4], [75, 6, 7])
toe3 = linalg.toeplitz([2.0, 3+2j, 6-1j])

print(toe1, '\n\n', toe2, '\n\n', toe3)

[[2 3 4]
 [3 2 3]
 [4 3 2]] 

 [[2 6 7]
 [3 2 6]
 [4 3 2]] 

 [[2.+0.j 3.-2.j 6.+1.j]
 [3.+2.j 2.+0.j 3.-2.j]
 [6.-1.j 3.+2.j 2.+0.j]]


## Van der Monde Matrix

In [77]:
# Assuming, numpy as np and scipy.linalg imported

# Generate a Vandermonde matrix
vm1 = np.vander(np.array([3, 5]), 5)
vm2 = np.vander(np.array([7, 4]))
vm3 = np.vander(np.array([6, 2]), 4, increasing=True)

print(vm1, '\n\n', vm2, '\n\n', vm3)

[[ 81  27   9   3   1]
 [625 125  25   5   1]] 

 [[7 1]
 [4 1]] 

 [[  1   6  36 216]
 [  1   2   4   8]]
